### ISSUE TITLE
listObjects throws BadCertificate error when bucket name has periods in it

### ISSUE THREAD

**Issue by wperron** [lucacasonato/deno_s3#15]
I get the following stack trace:

```text
$ deno run -A s3-upload.ts -b deno.wperron.io       
Sending fatal alert BadCertificate
error: Uncaught (in promise) Http: error sending request for url (https://deno.wperron.io.s3.ca-central-1.amazonaws.com/?list-type=2): error trying to connect: invalid certificate: CertNotValidForName
    at processResponse (core.js:224:13)
    at Object.jsonOpAsync (core.js:242:12)
    at async fetch (deno:op_crates/fetch/26_fetch.js:1274:29)
    at async S3Bucket.listObjects (bucket.ts:189:17)
    at async main (s3-upload.ts:77:25)
```

this only seems to happen on bucket names that contain periods in them

I'm running on Ubuntu 20.10 with Deno v1.5.3

**Comment by lucacasonato** [comment]
![image](https://user-images.githubusercontent.com/7829205/99316847-5783de80-2865-11eb-8f01-e5301cc6cfa3.jpeg)

![image](https://user-images.githubusercontent.com/7829205/99316856-5a7ecf00-2865-11eb-9db4-bf6c982bb1e2.jpeg)

The certificates are indeed invalid. Not a deno issue, rather a s3 issue.

**Comment by wperron** [comment]
This is weird, because curl doesn't return an invalid certificate issue

**Comment by wperron** [comment]
I'm reopening because I confirmed that the standard JS sdk uses the path-style bucket addressing instead of the subdomain style (https://s3.ca-central-1.amazonaws.com/deno.wperron.io) Also as per the [deprecation plan](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) the expected behaviors is that buckets containing periods use the older path-style addressing.

>Programmatic Access – If your application accesses S3 using one of the AWS SDKs, you don’t need to do anything, other than ensuring that your SDK is current. The SDKs already use virtual-hosted references to S3, except if the bucket name contains one or more “.” characters.
